site_name: Aspyx
site_url: https://coolsamson7.github.io/aspyx/
repo_url: https://github.com/coolsamson7/aspyx
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - palette.toggle
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home:
      - Motivation: index/motivation.md
      - Introduction: index/introduction.md
      - Installation: index/installation.md
      - Environment: index/environment.md
      - Configuration: index/configuration.md
      - AOP: index/aop.md
      - Reflection: index/reflection.md
      - Exceptions: index/exceptions.md
      - Threading: index/threading.md
      - Version History: index/versions.md

  - API Reference:
      - Util: api/util.md
      - Reflection: api/reflection.md
      - Configuration: api/configuration.md
      - Threading: api/threading.md
      - Exception: api/exception.md
      - DI: api/di.md
      - AOP: api/aop.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            docstring_style: google
            follow_imports: true