site_name: Aspyx
site_url: https://coolsamson7.github.io/aspyx/
repo_url: https://github.com/coolsamson7/aspyx
site_description: "Aspyx is a lightweight DI and AOP framework for Python."
site_author: "Andreas Ernst"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - palette.toggle
    - search.suggest
    - search.highlight
  markdown_extensions:
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.snippets
    - tables
    - toc:
        permalink: true
    - admonition
    - codehilite
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.magiclink
    - pymdownx.betterem
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.highlight
    - pymdownx.striphtml
    - pymdownx.autorefs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home:
      - Introduction: index/introduction.md
      - Installation: index/installation.md
      - Environment: index/environment.md
      - Configuration: index/configuration.md
      - AOP: index/aop.md
      - Reflection: index/reflection.md
      - Exceptions: index/exceptions.md
      - Threading: index/threading.md
      - Service: index/service.md
      - Version History: index/versions.md

  - API Reference:
      - Core:
        - Util: api/util.md
        - Reflection: api/reflection.md
        - Configuration: api/configuration.md
        - Threading: api/threading.md
        - Exception: api/exception.md
        - DI: api/di.md
        - AOP: api/aop.md
      - Service:
        - Service: api/service.md
        - Server: api/server.md
        - Registries: api/registries.md
        - Channels: api/channels.md
        - Health Checks: api/healthcheck.md
        - Session: api/session.md
        - Authorization: api/authorization.md


markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            docstring_style: google
            follow_imports: true
            merge_init_into_class: true
            merge_class_into_init: false