name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and hatch
        run: |
          python -m pip install --upgrade pip hatch pytest

      - name: Setup environment
        run: echo "PYTHONPATH=packages/aspyx/src:packages/aspyx_service/src" >> $GITHUB_ENV

      - name: Build aspyx package
        working-directory: packages/aspyx
        run: |
          hatch build
          pip install dist/*.whl
          pytest

      - name: Build aspyx_service package
        working-directory: packages/aspyx_service
        run: |
          hatch build
          pip install dist/*.whl
          pytest
