name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and hatch
        run: |
          python -m pip install --upgrade pip hatch

      - name: Install packages in editable mode
        run: |
          pip install -e packages/aspyx
          pip install -e packages/aspyx_service

      - name: Print current working directory
        run: ls -la

      - name: List files for debug
        run: |
          pwd
          ls -R packages/aspyx/src
          ls -R packages/aspyx_service/src

      - name: Build all packages
        run: hatch run build-all

      - name: Run all tests
        run: hatch run test