name: Deploy MkDocs

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and plugins
        run: |
          pip install mkdocs-material mkdocstrings[python]

      - name: Setup environment
        run: echo "PYTHONPATH=packages/aspyx/src:packages/aspyx_service/src::packages/aspyx_event/src" >> $GITHUB_ENV

      - name: Build docs
        run: mkdocs build

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force