name: Release

on:
  push:
    tags:
      - 'aspyx-v*'           # e.g., aspyx-v1.4.2
      - 'aspyx_service-v*'   # e.g., aspyx_service-v0.9.1
      - 'aspyx_event-v*'   # e.g., aspyx_service-v0.9.1

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/aspyx

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Hatch and Twine
        run: |
          python -m pip install --upgrade pip
          pip install hatch twine

      - name: Build & Publish aspyx
        if: startsWith(github.ref, 'refs/tags/aspyx-v')
        working-directory: packages/aspyx
        run: |
          hatch build
          twine upload dist/*

      - name: Build & Publish aspyx_service
        if: startsWith(github.ref, 'refs/tags/aspyx_service-v')
        working-directory: packages/aspyx_service
        run: |
          hatch build
          twine upload dist/*

      - name: Build & Publish aspyx_event
        if: startsWith(github.ref, 'refs/tags/aspyx_event-v')
        working-directory: packages/aspyx_event
        run: |
          hatch build
          twine upload dist/*

    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}