name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Test, Build, and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use your desired Python version

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD/src:$PWD/tests" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]  # assuming tests are defined in extras_require
          pip install build twine

      - name: Run tests
        run: |
          pip install pytest-xdist
          pytest --forked

      - name: Build the package
        run: |
          python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*